[[STANDARD]]
name = "XLS-2d"
title = "XRPL Destination format parser"
draft = true

[[STANDARD]]
name = "XLS-5"
title = "Tagged Addresses"
draft = false
documentation = "https://xrpaddress.info"
implementation = "https://www.npmjs.com/package/xrpl-tagged-address-codec"

[[STANDARD]]
name = "XLS-7"
title = "Deletable Accounts on the XRP Ledger"
draft = false
documentation = "https://xrpl.org/accountdelete.html"

[[STANDARD]]
name = "XLS-12"
title = "Secret Numbers"
draft = false
implementation = "https://www.npmjs.com/package/xrpl-secret-numbers"

[[STANDARD]]
name = "XLS-24d"
title = "NFT Schema"
draft = true

